name: Build & Deploy static page

on:
    workflow_dispatch: # enable manual triggering
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: denoland/setup-deno@v1
              with:
                deno-version: v1.x

            - name: Build static page
              run: deno task build

            - name: Upload pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  name: github-pages
                  path: _site

    deploy:
        needs: build
        runs-on: ubuntu-latest

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy pages
              uses: actions/deploy-pages@v4
              id: deployment
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
